
  trigger:
  - main

  variables:
    # Azure service connection established during pipeline creation
    azureSubscription: 'my service conn for fn demo'
    appName: 'func-app-yamchi'
    # Agent VM image name
    vmImageName: 'ubuntu-latest'
    
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      # archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
      archiveFile: $(System.ArtifactsDirectory)/build$(Build.BuildId).zip
  - task: PublishBuildArtifacts@1
    inputs:
      # PathtoPublish: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
      PathtoPublish: $(System.ArtifactsDirectory)/build$(Build.BuildId).zip
      # PathtoPublish: '$(Build.ArtifactStagingDirectory)/build$(Build.BuildId).zip'
      artifactName: 'drop'

  - task: AzureFunctionApp@1 # Add this at the end of your file
    inputs:
      azureSubscription: 'my service conn for fn demo'
      appType: functionAppLinux # default is functionApp
      appName: $(appName)
      package: $(System.ArtifactsDirectory)/**/*.zip
      # package: $(Build.ArtifactStagingDirectory)/**/*.zip
      #Uncomment the next lines to deploy to a deployment slot
      #Note that deployment slots is not supported for Linux Dynamic SKU
      #deployToSlotOrASE: true
      #resourceGroupName: '<Resource Group Name>'
      #slotName: '<Slot name>'